### ISSUE TITLE
WordPress health check error: curl: (60) SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by emmtre** [FiloSottile/mkcert#165] opened 2019-05-26 12:33 UTC
It this a known issue with macOS Mojave (10.14.5)? I have problems with site health check in WordPress 5.2.1 and REST API and loopback requests.

```
curl https://local.website.com
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

**Comment by emmtre** [comment] 2019-05-26 13:16
Do you have to set curl.cainfo and openssl.cafile in the php.ini file?

**Comment by emmtre** [comment] 2019-05-26 17:19
```
curl -v https://local.website.com

* Rebuilt URL to: https://local.website.com/
* Trying ::1...
* Connected to local.website.com (::1) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* Successfully set certificate verify locations:
* CAfile: /share/curl/curl-ca-bundle.crt
* CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0

curl: (60) SSL certificate problem: unable to get local issuer certificate
```

**Comment by Cobs** [comment] 2019-05-31 17:31
I got the same message with Debian.
Fixed it by manualy adding the mkcert's CA Certificate into the local CA cert store and set the extention from .pem to .crt

**Comment by emmtre** [comment] 2019-05-31 19:10
The CA Certificate is added to the macOS system store automatically. When using `/usr/bin/curl` everything is working as expected. But WordPress is using it's own version of `curl` so the installed mkcert's CA Certificate is not found. I have also tried to set `curl.cainfo` without success. Any other ideas?

`curl.cainfo=/Users/Username/Library/Application\ Support/mkcert/rootCA.pem`

**Comment by healdev** [comment] 2019-05-31 23:13
Same problem here...
Running WordPress 5.2.1 on local OS X Mojave
curl command works with no issue in terminal but WordPress HealthCheck throws a curl error 60... for REST API and Loopback requests.

Anybody solved that?

ps: @emmtre not sure but shouldn't the path be wrapped in double quotes for the curl.cainfo setting?

**Comment by healdev** [comment] 2019-05-31 23:24
The only hack I could find on my local dev environment is to manually edit /wp-includes/certificates/ca-bundle.crt and append the content of /Users/Username/Library/Application\ Support/mkcert/rootCA.pem to end of file
That solved the problem, I just need to find a long-term solution...maybe a must-use plugin that would check and edit the file automatically... or I'll try to find a hook

**Comment by healdev** [comment] 2019-05-31 23:48
Ok so there is a filter to deal with this issue.
Since I have this issue only on my local dev env, I created a must-use plugin that checks if the environment is local and looks for certificate in the desired file.

if ( '127.0.0.1' === $_SERVER['REMOTE_ADDR'] ) {
	add_filter( 'http_request_args', function( $r, $url ) {
		$r['sslcertificates'] = '/Users/<YOUR-USERNAME>/.localhost_ssl/cacert.pem';
		return $r;
	}, 10, 2);
}

**Comment by FiloSottile** [comment] 2019-06-01 12:30
Yeah, WordPress is configuring curl to use a hardcoded CA list, so there's not much mkcert can do.

```
* Successfully set certificate verify locations:
* CAfile: /share/curl/curl-ca-bundle.crt
```

Closing this as it's not a mkcert issue, but thanks for providing a workaround, and maybe consider opening an issue with WordPress to use the system store, I don't think there's any good reason not to.

**Closed by FiloSottile** 2019-06-01 12:30 UTC

**Comment by simongcc** [comment] 2020-02-25 09:15
@healdev I am meeting the same situation. And found that there is a filter for updating the path. I have created a certificate for local use and point to that by calling the filter and put it inside `functions.php`.

```
add_filter( 'http_request_args', 'modify_ca_cert_location', 10, 2 );
function modify_ca_cert_location( $r ) {
	$r['sslcertificates'] = WP_CONTENT_DIR.'/themes/wp-theme-name/ssl/ca-bundle.crt';
	return $r;
}
```

**Comment by simongcc** [comment] 2020-03-01 15:18
@healdev 
Ops, I think I have overlooked and missed your solutions by just scanning through without reading in depth.
Sorry about that.

**Comment by Kevinlearynet** [comment] 2020-04-19 01:35
This isn't an issue with `mkcert`, it's ultimately something caused by the way WordPress handles cURL requests. Here's the specific line causing it:

https://github.com/WordPress/WordPress/blob/856e1a27b8dfa9208c36b8b474afcb5acc90322b/wp-includes/class-http.php#L209

I've fixed this myself in a Homebrew installed PHP 7.4 localhost using this function:

```
/**
 * Replace Localhost cURL Certificates
 *
 * If the URL for an HTTP request in WordPress contains a .test
 * TLD, replace the WordPress local /certificates/ca-bundle.crt
 * with the PHP supplied bundle.
 */
function curl_patch_http_request_args( $parsed_args, $url ) {

	// Request URL points to a *.test host
	$test_tld = end( explode( ".", parse_url( $url, PHP_URL_HOST ) ) );
	if ( ! $test_tld ) return $parsed_args;

	// Replace WordPress local certificates with PHP's default cacert path
	$openssl_cert_locations = openssl_get_cert_locations();
	if ( isset( $openssl_cert_locations['default_cert_file'] ) ) {
		$parsed_args['sslcertificates'] = $openssl_cert_locations['default_cert_file']
	}

	return $parsed_args;
}
add_filter( 'http_request_args', [ $this, 'curl_patch_http_request_args' ], 99, 2 );
```

This will filter all HTTP class instances, replacing the locally used cURL certificate authority at `/wp-includes/certificates/ca-bundle.crt` with the certificate authority currently used by PHP for any request to a *.test TLD. I use .test domains locally, but if you use other URL's be sure to adjust this part.

**Comment by netnaps** [comment] 2020-06-24 14:35
i had the same issue it was just because of another plugin named really simple ssl , deactivated the same and it worked.

**Comment by petertwise** [comment] 2020-09-23 02:17
Thanks for the great research on this issue everyone. I made some of the solutions presented here into a dropin plugin:
https://github.com/squarecandy/force-localhost-ca

**Comment by nylen** [comment] 2020-10-16 19:05
> maybe consider opening an issue with WordPress to use the system store, I don't think there's any good reason not to

For what it's worth, there are very good reasons not to use the system cert store. One of them is that WordPress and ClassicPress run on a very wide variety of servers, which includes servers that unfortunately have not been updated in a long time. This would cause many legitimate requests to fail.

**Comment by Werverton** [comment] 2021-12-16 15:58
> I got the same message with Debian. Fixed it by manualy adding the mkcert's CA Certificate into the local CA cert store and set the extention from .pem to .crt

In which local?

**Comment by Cobs** [comment] 2021-12-19 20:23
> > I got the same message with Debian. Fixed it by manualy adding the mkcert's CA Certificate into the local CA cert store and set the extention from .pem to .crt
> 
> In which local?

I'm not sure i understand the question.
As told in the [update-ca-certificate program's manual](https://www.unix.com/man-page/linux/8/update-ca-certificates/), I just copied the mkcert certificate in /usr/local/share/ca-certificates as a .crt file then ran update-ca-certificate

**Comment by Werverton** [comment] 2021-12-20 04:22
In my case, I solved the problem inserting the SSLCACertificate /Path/to/domain.ca-bundle in virtual host .conf . The cURL needs the Chain of certificate.
