### ISSUE TITLE
"NET::ERR_CERT_AUTHORITY_INVALID" in Chrome on macOS

### ISSUE THREAD

**Issue by kenny-evitt** [FiloSottile/mkcert#180] opened 2019-07-22 15:51 UTC
My computer is running macOS version "10.14.5 (18F132)". I'm testing in Chrome version "75.0.3770.142 (Official Build) (64-bit)". Chrome was updated recently, i.e. yesterday, from an unknown earlier version (tho fairly recent I think).

Several days ago `mkcert` seemed to be working as expected. Today I get the error mentioned in the title.

I was able to get it working again by manually adding the certificate to my "login" "Certificates" in the *Keychain Access* app by following the steps in [this answer](https://superuser.com/a/1235250/37845) to the following Super User question:

 - [ssl - How do I deal with NET:ERR_CERT_AUTHORITY_INVALID in Chrome? - Super User](https://superuser.com/questions/1083766/how-do-i-deal-with-neterr-cert-authority-invalid-in-chrome)

This might be related to this recently opened issue:

 - ["Certificate is not standards compliant" on macOS Catalina · Issue #174](https://github.com/FiloSottile/mkcert/issues/174)

**Comment by ngdot** [comment] 2019-08-01 22:14
sane problem here!

**Comment by robo360** [comment] 2019-08-06 20:04
Same problem

**Comment by daquinoaldo** [comment] 2019-08-21 15:48
In my case works on MacOS (Mojave) but not on Ubuntu 1

**Comment by rfay** [comment] 2019-08-21 17:12
Please say more about how you're doing your testing @daquinoaldo - and this is mkcert v1.4.0 true? 

BTW, I'm quite sure this is a dup of https://github.com/FiloSottile/mkcert/issues/174 and this one should be closed.

**Comment by rfay** [comment] 2019-08-22 02:54
My experience testing on Ubuntu 19.04 is that both Chromium and Firefox accept the not-before-June-1 certs generated by mkcert v1.4.0. @daquinoaldo if you look at the "Not-valid-before" in your browser's presentation of the cert and it was generated by v1.4.0, you should see May 31, 2019 or June 1, 2019, depending on your timezone.

**Comment by daquinoaldo** [comment] 2019-08-22 13:09
@rfay sorry, my fault: I changed laptop and I forgot to install libnss3-tools.

**Comment by kenny-evitt** [comment] 2019-08-22 13:43
@rfay I'm less sure this a duplicate of #174 – for one the error is different. The error I observed seems more 'severe'.

**Comment by rfay** [comment] 2019-08-22 13:52
I use the Chrome official build on macOS quite successfully with mkcert on macOS.  Daily. And wasn't having any trouble with v1.3.0. I wonder what this is.

**Comment by mrtimp** [comment] 2019-09-25 22:55
I'm having this issue on macOS 10.14.6 in Safari, Chrome and Firefox after a fresh install of macOS. None of the suggested fixes work for me.

**Comment by rfay** [comment] 2019-09-25 23:00
@mrtimp Please confirm that you are using mkcert v1.4.0, and you ran `mkcert -install` and then created new certs with mkcert v1.4.0?

**Comment by mrtimp** [comment] 2019-09-25 23:10
Apologies @rfay, turned out that I wasn't mounting the newly created certificates into my container, it was using the certificates from a previous install.  Once I spotted that the serial number on the certificate didn't match I knew where the issue was.  

Cheers for the prompt reply :-)

**Comment by FiloSottile** [comment] 2019-11-09 22:48
I don't have any idea what this would be due to. It looks like it hasn't been happening much recently though? If anyone is still experiencing this, please post exact Chrome, macOS, and mkcert versions, as well as the error screenshot.

**Comment by rushi** [comment] 2019-11-11 03:06
@FiloSottile This is happening for me using mkcert **v1.4.0**, Chrome Version **78.0.3904.87** (Official Build) (64-bit), on MacOS **Catalina** v10.15.
<img width="848" alt="image" src="https://user-images.githubusercontent.com/65708/68558154-3f150300-045e-11ea-9a89-eae687fd4a30.png">

**Comment by osadchiynikita** [comment] 2019-11-13 12:36
@rushi If you still need to proceed, try to Enable this flag

chrome://flags/#allow-insecure-localhost

**Comment by jordito** [comment] 2019-11-14 19:23
@FiloSottile Unfortunately I'm having the same issue with mkcert v1.4.0, Chrome 78.0.3904.97 (Official Build) (64-bit), on MacOS Mojave 10.14.6

![Screenshot 2019-11-14 at 20 15 28](https://user-images.githubusercontent.com/18441852/68889080-80d2d180-071c-11ea-8dc2-e3047744f983.png)


@osadchiynikita Your tip sounded promising but unfortunately didn't do the trick for me. Thanks though.

**Comment by sup2007** [comment] 2019-11-28 10:44
same here

- mkcert 1.4.1 (brew)
- mac os catalina 10.15.1
- Chrome 78.0.3904.108 (64bit) (+Firefox, Firefox Dev, Chrome Canary, ...)

**Comment by FlorentTorregrosa** [comment] 2020-01-19 18:39
Hello,

I tried to follow tutorials to have traefik using certificates generated by mkcert, but I think I have the same issue has described here.

- mkcert 1.4.1 (downloaded from github)
- Chromium Version 79.0.3945.79 (Build officiel) Built on Ubuntu , running on LinuxMint 19.1 (64 bits)

Here are the scripts I was making in WIP to test, and this is the order of execution:
- https://github.com/FlorentTorregrosa/docker-drupal-project/blob/traefik_https/conf/traefik/install-mkcert.sh
- https://github.com/FlorentTorregrosa/docker-drupal-project/blob/traefik_https/conf/traefik/generate-local-certificate.sh
- docker-compose for traefik: https://github.com/FlorentTorregrosa/docker-drupal-project/blob/traefik_https/conf/traefik/docker-compose.yml
- traefik config: https://github.com/FlorentTorregrosa/docker-drupal-project/blob/traefik_https/conf/traefik/traefik.yml
- docker-compose for the app (I was testing the mailcatcher before extending to the whole app): https://github.com/FlorentTorregrosa/docker-drupal-project/blob/traefik_https/docker-compose.yml

I have the HTTP -> HTTPS redirection ok, but still NET::ERR_CERT_AUTHORITY_INVALID if I go to https://mail-ddp8.docker.localhost/

Thanks for any help.

**Comment by FlorentTorregrosa** [comment] 2020-01-26 14:40
Hello,

I found the problem. It was not related to mkcert but to Traefik. The generated certificates were not loaded into Traefik configuration.

I smelled the problem when seing that the invalid certificate name was "TREAFIK DEFAULT CERTIFICATE".

**Comment by rushi** [comment] 2020-05-09 04:52
> @FiloSottile This is happening for me using mkcert v1.4.0, Chrome Version 78.0.3904.87 (Official Build) (64-bit), on MacOS Catalina v10.15.

My problem was resolved and it was user error. Bad configuration in Apache

**Comment by FiloSottile** [comment] 2020-07-02 18:06
I still haven't been able to ever reproduce this.

Here's some more info that might help if anyone who's encountering this wants to report it:

* output of `security dump-trust-settings` and `security dump-trust-settings -d`
* screenshot of the certificate viewer (click on the lock > click on "Certificate")
* output of `cat "$(mkcert -CAROOT)/rootCA.pem"`

**Comment by jaykobi** [comment] 2020-09-09 08:02
I had the same error, then tried all over again and it worked. It turned out the first time I created the certs (mkcert mydomain.com xxx) with sudo (Which obviously did not find the CA)

**Comment by FiloSottile** [comment] 2020-10-25 23:41
Closing as this has not occurred in a while. I suspect these were various forms of operational issues where the root did not end up installed, or the certificate did not end up loaded in the web server.

If anyone were to encounter this error again, please open a new issue and provide the details listed here:
https://github.com/FiloSottile/mkcert/issues/180#issuecomment-653149738

**Closed by FiloSottile** 2020-10-25 23:41 UTC
Labels: waiting for info

**Comment by jartaud** [comment] 2020-11-20 23:43
> I had the same error, then tried all over again and it worked. It turned out the first time I created the certs (mkcert mydomain.com xxx) with sudo (Which obviously did not find the CA)

Yep, I was having 2 issues:

1. I was using sudo

2. I was creating the certs in `/home/me/code/ssl`  while the local CA is sittiing at `/home/me/.local/share/mkcert`

Generating the certs in `/home/me` without sudo and the copy them to `/home/me/code/ssl` works great.

**Comment by erosenberg** [comment] 2020-12-20 22:16
I am also having this issue on Ubuntu 16.04. I've tried doing the above, but maybe I'm doing something wrong since I might not be using it for its intended purpose.
Essentially, I have a NUC that I use as a server, and I have my laptop.
I'm running some services on my NUC and am proxying them behind traefik.
I am using Pihole as my DNS provider, and configured it so that `nuc.lan` points me to my traefik instance.
On my NUC, I have installed mkcert (`libnss3-tools`) and didn't use sudo when I ran:
`mkcert -install`. I just ran it again and am seeing:
```
The local CA is already installed in the system trust store! 👍
The local CA is already installed in the Firefox and/or Chrome/Chromium trust store! 👍
```
Then I ran:
`mkcert nuc.lan '*.nuc.lan' localhost 127.0.0.1 ::1`

The following files are created:

- nuc.lan+4-key.pem
- nuc.lan+4.pem

Then in my Traefik I set my TLS certificates to be the ones that mkcert created:

```
tls:
  certificates:
    - certFile: /etc/certs/htpc.lan+4.pem
      keyFile: /etc/certs/htpc.lan+4-key.pem
```

In my browser(s), I see some variation of the same thing: 

```
Issued by: mkcert eitan@nuc (Eitan R)
"eitan@nuc (Eitan R)" certificate is not trusted.
```

Am I missing something here?

**Comment by CodyEddings** [comment] 2021-01-28 20:35
@FiloSottile  I'm also having an untrusted certificate error (`NET::ERR_CERT_AUTHORITY_INVALID`) trying to use https in my localhost Vue CLI app, following Chad Carter's answer [here ](https://stackoverflow.com/questions/45807049/how-to-run-vue-js-dev-serve-with-https).

![image](https://user-images.githubusercontent.com/17996938/106195449-276a8d00-617e-11eb-80de-7dd7991783f0.png)

**vue.config.js**
```
const fs = require('fs')

module.exports = {
    devServer: {
        https: {
          key: fs.readFileSync('./certs/example.com+5-key.pem'),
          cert: fs.readFileSync('./certs/example.com+5.pem'),
        },
        public: 'https://localhost:8084/'
    }
}
```

**Comment by CodyEddings** [comment] 2021-01-28 20:37
Fixed the issue! the problem was I had never run `mkcert -install` locally on my windows terminal before creating the cert files

**Comment by wkdcode-liam** [comment] 2021-02-19 16:33
@CodyEddings I am having the same issue, where did you run mkcert -install ? inside command prompt? I am using Ubuntu 20.04 as a local apache server

**Comment by ltroya-as** [comment] 2021-06-16 16:36
@CodyEddings that command solves my problem on Windows, thanks.

@wkdcode-liam run it on the command prompt. If you are using docker, don't generate the certs on the container, generate on your local OS and use a volume to mount the certificates on the  container

**Comment by Valikkun** [comment] 2021-08-18 20:33
i use nginx in wsl2 localy. Got same error. It is fixed when:
- install mkcert on windows (powershell)
- mkcert -install (powershell)
- mkcert example.com (powershell)
- copy certs from windows in wsl and use them in nginx

**Comment by luizxsoto** [comment] 2024-03-16 18:44
tks @Valikkun, you solved my problem!

**Comment by PyPiSan** [comment] 2024-04-02 07:25
I had also faced the same issue, however, I had not run the mkcert -install command before creating the certificate.

**Comment by henriquebonfim** [comment] 2024-10-11 12:04
**_For those who use [Windows Subsystem for Linux (WSL)](https://learn.microsoft.com/en-us/windows/wsl/about)_**

Today, I found the same issue, and the tips from @Valikkun helped me understand the problem.

When we use a Linux environment inside Windows, we need to remember that it’s just a module, so it’s necessary to create a trusted certificate in the base OS (_Windows_) and share it, as @FiloSottile [says here](https://github.com/FiloSottile/mkcert?tab=readme-ov-file#changing-the-location-of-the-ca-files).

 * (PowerShell) install [mkcert on Windows](https://github.com/FiloSottile/mkcert?tab=readme-ov-file#windows) 
* (PowerShell) Run `mkcert -install`
* (PowerShell) Run `mkcert localhost` _or any other domain_
* (PowerShell) Run `mkcert -CAROOT` to get the location of the root CA inside Windows
* (Bash) Run `mkcert -CAROOT` to get the location of the root CA inside WSL
* (Bash) `cp -r <WIN_CAROOT_FOLDER> <LINUX_CAROOT_FOLDER>`
* (Bash) Run `mkcert -install`

After that, all secure!
![image](https://github.com/user-attachments/assets/f6b8a09b-268b-4df7-a124-b6f407cc9121)

My issue was with [Next.js using HTTPS during development](https://nextjs.org/docs/app/api-reference/cli/next#using-https-during-development), being unable to validate the SSL certificates inside WSL.

```JSON
  "scripts": {
    "dev": "next dev --experimental-https --experimental-https-key ./certificates/localhost-key.pem --experimental-https-cert ./certificates/localhost.pem",
    "build": "next build",
    "start": "next start"
  },
```

**Comment by dtamas020** [comment] 2025-01-15 10:35
> i use nginx in wsl2 localy. Got same error. It is fixed when:
> 
>     * install mkcert on windows (powershell)
> 
>     * mkcert -install (powershell)
> 
>     * mkcert example.com (powershell)
> 
>     * copy certs from windows in wsl and use them in nginx

Its worked for me.
I am running an ubuntu server with nginx.
I made a cert with mkcert on ubuntu and i had the
"ERR_CERT_AUTHORITY_INVALID" error in windows Chrome and 
"SEC_ERROR_UNKNOWN_ISSUER" error in windows Firefox.

I switched to Windows, 
  - installed mkcert, 
  - made the cert with the same params, 
  - copied to ubuntu, 
  - restarted nginx (the file name was the same) 
and it worked without any problem.

(It only prevents the error message from the machine where the cert was made)

**Comment by felipebsouza** [comment] 2025-08-04 12:22
> Fixed the issue! the problem was I had never run `mkcert -install` locally on my windows terminal before creating the cert files

same here! the script I was using ran this command, but apparently it showed an error that I didn't spot. after running it manually this issue was fixed. thanks!
