### ISSUE TITLE
Installation of root CA for OpenSSL

### ISSUE THREAD

**Issue by mglaman** [FiloSottile/mkcert#295] opened 2020-09-14 03:05 UTC
👋 This is a follow up to a tweet I made earlier: https://twitter.com/nmdmatt/status/1305206184094445571

Basically, PHP sockets fail to connect to a site using certificates with mkcert. That is because the `openssl.capath` does not contain the mkcert root CA.

**Comment by FiloSottile** [comment] 2020-10-25 17:21
Thank you, this is a duplicate of #199!

**Closed by FiloSottile** 2020-10-25 17:21 UTC
